name       : python-patch
version    : 1.16
release    : 2
source     :
    - https://pypi.python.org/packages/da/74/0815f03c82f4dc738e2bfc5f8966f682bebcc809f30c8e306e6cc7156a99/patch-1.16.zip : c62073f356cff054c8ac24496f1a3d7cfa137835c31e9af39a9f5292fd75bd9f
license    : MIT
component  : programming.python
summary    : Patch utility to apply unified diffs
description: |
    Patch utility to apply unified diffs
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
